name: LAW

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  law_production:
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Pull
      run: sudo git pull origin main
      working-directory: /var/www/html/law-web
    - name: Complete
      run: sudo npm run production
      working-directory: /var/www/html/law-web
